# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzdjMjUzMzdjM2ZiZjRhYTQ2NzZhZjg3ZmY0ZDBmNTZlMTM1ZTU0N2JiYTU5YWRlY2UxNjQyNTU0YzU3NDQyYjM1YmM1OWJjMjgwYjlkZDhlZTg4N2MxMzliNGJhMjVmYzY3OWViODJjZTY1YTEzZjcxOTc1YTgwMTM5MGVjNDY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
